# Generated by Django 3.2.13 on 2022-09-09 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travels',
            old_name='created_at',
            new_name='date_date',
        ),
        migrations.RenameField(
            model_name='travels',
            old_name='updated_at',
            new_name='start_date',
        ),
    ]
