# Generated by Django 3.2.13 on 2022-09-09 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_auto_20220909_0913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travels',
            old_name='date_date',
            new_name='end_date',
        ),
    ]
