# Generated by Django 3.2.13 on 2022-10-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_article_like_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='like_user',
            new_name='like_users',
        ),
    ]
